[workspace]
members = [
  "crates/cnf-sat-sorter",
]

[package]
name = "sat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memmap2 = "0.9.4"
rustc-hash = "2.0.0"
